config/routes.rb
Rails.application.routes.draw do
  resources :queries
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root 'queries#index', as: :authenticated_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :results
  resources :inbox
end

app/models/query.rb
class Query < ApplicationRecord
  VALID_SOURCES = {
    'FSBO' => 'http://fsbo.com'
  }

  has_many :results

  def query
    agent = Mechanize.new
    agent.user_agent_alias = "Windows IE 7"
    page = agent.get("http://fsbo.com")
    form = page.form_with(dom_id: 'basicSearchForm')
    form.searchQuery = location
    page = form.submit
    listing_links = page.links_with(css: '.fsbo-button')
    listing_links.each do |listing_link|
      if listing_link.text == "View Listing Details"
        page = listing_link.click
        html = Nokogiri::HTML(page.body)
        price = html.css('.address-copy > .price').text.strip.gsub(/\t/, "")
        address = html.css('.address-copy > .address').text.strip.gsub(/\t/, "").gsub(/\n/, "")
        details = []
        html.css('.listing-data > tr').each_with_index do |row, i|
          details[i] = row.search('td').map(&:text)
        end
        description = html.css('.property-description').text
        amenities = []
        html.css('.amenities > .more-amenities > ul > li').each do |amenity|
          amenities << amenity.text
        end
        page.links_with(text: "Contact Owner").first.click
        contact_info = html.css('.modal-body > div:first-child').css('.col-md-10').map(&:text).map(&:strip)

        detail_results = details.inject({}) do |hsh, detail|
          hsh.merge!(detail.first.gsub(":", "") => detail.second)
          hsh
        end

        result = results.new(
            listing_id: detail_results["Listing Id"],
            bedrooms: detail_results["Bedrooms"],
            bathrooms: detail_results["Bahtrooms"],
            garage: detail_results["Garage"],
            result_type: detail_results["Type"],
            subtype: detail_results["Subtype"],
            lot_size: detail_results["Lot Size"],
            square_feet: detail_results["Sq. Feet"],
            year_built: detail_results["Year Built"],
            school_district: detail_results["School District"],
            subdivision: detail_results["Subdivision"],
            price: price,
            address: address,
            description: description,
          )

        contact_information = result.contact_informations.new(
            name: contact_info.first
          )

        contact_information.phone_numbers.new(
            number: contact_info.second
          )
      end
    end
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [:show]

  def index
    @queries = Query.all.order(created_at: :desc)
  end

  def new
    @query = Query.new
  end

  def create
    @query_object = Query.new(query_params)
    @query_object.name = "#{@query_object.source} #{@query_object.location}"

    results = @query_object.query

    if @query_object.save
      flash[:notice] = "Query created."
      redirect_to queries_path
    else
      render :action => :new
    end
  end

  def show
    @results = @query.results
  end

  def destroy
    @query = Query.find(params[:id])

    if @query.destroy
      flash[:notice] = "Query destroyed."
      redirect_to queries_path
    else
      render action: :edit
    end
  end

  private

  def query_params
    params.require(:query).permit(:source, :location)
  end

  def set_query
    @query = Query.find(params[:id])
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/index.html.haml
= link_to "Create new Query", new_query_path

%table.table.table-bordered
  %tr
    %th Name
    %th Location
    %th Created On
    %th
  - @queries.each do |query|
    %tr
      %td= link_to query.name, query_path(query)
      %td= query.location
      %td= query.created_at.strftime("%m/%d/%Y")
      %td= link_to "Delete", query_path(query), method: 'Delete'

app/views/queries/new.html.haml
= simple_form_for @query do |f|
  = f.input :location
  = f.input :source, as: :select, collection: Query::VALID_SOURCES.keys

  = f.submit

app/views/queries/show.html.haml
= link_to 'Back', queries_path

- @results.each do |result|
  .panel.panel-default
    .panel-heading
      = "#{result.contact_informations.first.name} - #{result.contact_informations.first.phone_numbers.first.number}"
    %table.table.table-bordered
      %tr
        %td{colspan: 12}= result.description
      %tr
        %th Address
        %th Price
        %th Bedrooms
        %th Bathrooms
        %th Garage
        %th Type
        %th Subtype
        %th Lot Size
        %th Square Feet
        %th Year Built
        %th School District
        %th Subdivision
      %tr
        %td= result.address
        %td= result.price
        %td= result.bedrooms
        %td= result.bathrooms
        %td= result.garage
        %td= result.result_type
        %td= result.subtype
        %td= result.lot_size
        %td= result.square_feet
        %td= result.year_built
        %td= result.school_district
        %td= result.subdivision